// export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
// export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
// export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';

// export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
// export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
// export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

// export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
// export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
// export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

// export const RESET_USER: 'RESET_USER' = 'RESET_USER';

// export const PASSWORD_FORGOT_REQUEST: 'PASSWORD_FORGOT_REQUEST' =
//   'PASSWORD_FORGOT_REQUEST';
// export const PASSWORD_FORGOT_SUCCESS: 'PASSWORD_FORGOT_SUCCESS' =
//   'PASSWORD_FORGOT_SUCCESS';
// export const PASSWORD_FORGOT_FAILED: 'PASSWORD_FORGOT_FAILED' =
//   'PASSWORD_FORGOT_FAILED';

// export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' =
//   'GET_INGREDIENTS_REQUEST';
// export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' =
//   'GET_INGREDIENTS_SUCCESS';
// export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' =
//   'GET_INGREDIENTS_FAILED';

// export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
// export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';

// export const OPEN_INGREDIENTS_DETAILS: 'OPEN_INGREDIENTS_DETAILS' =
//   'OPEN_INGREDIENTS_DETAILS';
// export const CLOSE_INGREDIENTS_DETAILS: 'CLOSE_INGREDIENTS_DETAILS' = "CLOSE_INGREDIENTS_DETAILS"; // prettier-ignore

// export const REORDER_INGREDIENTS: 'REORDER_INGREDIENTS' = 'REORDER_INGREDIENTS';

// export const SHOW_MODAL: 'SHOW_MODAL' = 'SHOW_MODAL';
// export const HIDE_MODAL: 'HIDE_MODAL' = 'HIDE_MODAL';

// export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' =
//   'CREATE_ORDER_REQUEST';
// export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' =
//   'CREATE_ORDER_SUCCESS';
// export const CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED' = 'CREATE_ORDER_FAILED';

// export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';

// export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' =
//   'REFRESH_TOKEN_REQUEST';
// export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' =
//   'REFRESH_TOKEN_SUCCESS';
// export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' =
//   'REFRESH_TOKEN_FAILED';

// export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
// export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
// export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

// export const PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST' =
//   'PASSWORD_RESET_REQUEST';
// export const PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS' =
//   'PASSWORD_RESET_SUCCESS';
// export const PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED' =
//   'PASSWORD_RESET_FAILED';

// export const SELECT_BUNS_TAB: 'SELECT_BUNS_TAB' = 'SELECT_BUNS_TAB';
// export const SELECT_SAUCES_TAB: 'SELECT_SAUCES_TAB' = 'SELECT_SAUCES_TAB';
// export const SELECT_MAINS_TAB: 'SELECT_MAINS_TAB' = 'SELECT_MAINS_TAB';

// export const WS_FEED_CONNECTION_START: 'WS_FEED_CONNECTION_START' =
//   'WS_FEED_CONNECTION_START';
// export const WS_FEED_CONNECTION_SUCCESS: 'WS_FEED_CONNECTION_SUCCESS' =
//   'WS_FEED_CONNECTION_SUCCESS';
// export const WS_FEED_CONNECTION_ERROR: 'WS_FEED_CONNECTION_ERROR' =
//   'WS_FEED_CONNECTION_ERROR';
// export const WS_FEED_CONNECTION_CLOSED: 'WS_FEED_CONNECTION_CLOSED' =
//   'WS_FEED_CONNECTION_CLOSED';
// export const WS_FEED_GET_MESSAGE: 'WS_FEED_GET_MESSAGE' = 'WS_FEED_GET_MESSAGE';
// export const WS_FEED_SELECT: 'WS_FEED_SELECT' = 'WS_FEED_SELECT';

// export const WS_ORDERS_CONNECTION_START: 'WS_ORDERS_CONNECTION_START' =
//   'WS_ORDERS_CONNECTION_START';
// export const WS_ORDERS_CONNECTION_SUCCESS: 'WS_ORDERS_CONNECTION_SUCCESS' =
//   'WS_ORDERS_CONNECTION_SUCCESS';
// export const WS_ORDERS_CONNECTION_ERROR: 'WS_ORDERS_CONNECTION_ERROR' =
//   'WS_ORDERS_CONNECTION_ERROR';
// export const WS_ORDERS_CONNECTION_CLOSED: 'WS_ORDERS_CONNECTION_CLOSED' =
//   'WS_ORDERS_CONNECTION_CLOSED';
// export const WS_ORDERS_GET_MESSAGE: 'WS_ORDERS_GET_MESSAGE' =
//   'WS_ORDERS_GET_MESSAGE';
export const WS_ORDERS_SELECT: 'WS_ORDERS_SELECT' = 'WS_ORDERS_SELECT';
